FROM centos

RUN  yum -y install openssh-server

RUN usseradd remote_user && \
    echo "1234" | passswd remote_user --stdin && \
    mkdir /home/remote_user/.ssh && \
    chmod 700 /home/remote_user/.ssh 

COPY remote-key.pub /home/remote_user/.shh/authorized-keys

RUN chwon remote_user:remote_user -R /home/remote_user && \
    chmod 600 /home/remote_user/.ssh/authorized_keys

RUN /usr/sbin/sshd.keygen > /dev/null 2>&1

CMD /usr/sbin/sshd -D